# filename: auth-service.yaml
openapi: 3.0.3
info:
  title: Auth Service API
  version: 2.5.0
  description: |
    سرویس مرکزی احراز هویت و مجوزدهی پلتفرم بازار خرده‌فروشی مواد غذایی  
    معماری CQRS: Write Side (SQL Server) | Read Side + Logs (PostgreSQL)  
    پشتیبانی کامل از ثبت‌نام OTP، JWT داخلی/خارجی، UserGroup + Operation برای منوی داینامیک
servers:
  - url: https://api.marketplace.local/auth
    description: Production
  - url: https://api.marketplace.sbx/auth
    description: Sandbox

tags:
  - name: Public
    description: عملیات عمومی (بدون احراز هویت)
  - name: Authentication
    description: ورود، ثبت‌نام، OTP، توکن
  - name: Profile
    description: پروفایل و منوی کاربر جاری
  - name: Admin
    description: مدیریت کاربران، گروه‌ها و عملیات (فقط SystemAdmin)

paths:
  # ثبت‌نام و OTP
  /api/public/register:
    post:
      tags: [Public]
      summary: ثبت‌نام کاربر جدید (مشتری یا فروشنده)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: کاربر ایجاد شد – OTP ارسال شد
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'

  /api/public/verify-otp:
    post:
      tags: [Public]
      summary: تأیید OTP (ثبت‌نام، ورود، تغییر موبایل)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtpRequest'
      responses:
        '200':
          description: تأیید موفق – توکن صادر شد
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  # ورود با رمز
  /api/public/login/password:
    post:
      tags: [Public]
      summary: ورود با موبایل و رمز عبور
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordLoginRequest'
      responses:
        '200':
          description: ورود موفق
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  # ورود با OTP
  /api/public/login/otp/request:
    post:
      tags: [Public]
      summary: درخواست ارسال OTP برای ورود
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [mobile]
              properties:
                mobile:
                  type: string
                  pattern: ^\+98\d{10}$
      responses:
        '202':
          description: OTP ارسال شد

  # نوسازی توکن
  /api/auth/refresh:
    post:
      tags: [Authentication]
      summary: نوسازی توکن دسترسی
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  /api/auth/logout:
    post:
      tags: [Authentication]
      summary: خروج و ابطال توکن
      security:
        - bearerAuth: []
      responses:
        '204': {}

  # پروفایل و منو (Read Side – PostgreSQL)
  /api/users/me:
    get:
      tags: [Profile]
      summary: پروفایل کامل کاربر جاری (با گروه‌ها و دسترسی‌ها)
      security:
        - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserDto'

  /api/users/me/menu:
    get:
      tags: [Profile]
      summary: منوی داینامیک کاربر (از PostgreSQL Read Model)
      security:
        - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItemDto'

  # مدیریت توسط ادمین (Write Side – SQL Server)
  /api/admin/users:
    get:
      tags: [Admin]
      summary: جستجوی کاربران
      security:
        - bearerAuth: [SystemAdmin]
      parameters:
        - name: mobile
          in: query
          schema: { type: string }
        - name: groupCode
          in: query
          schema: { type: string }
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: pageSize
          in: query
          schema: { type: integer, default: 20 }
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedUserAdminDto'

  /api/admin/user-groups:
    get:
      tags: [Admin]
      summary: لیست گروه‌های کاربری
      security:
        - bearerAuth: [SystemAdmin]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroupDto'

    post:
      tags: [Admin]
      summary: ایجاد گروه جدید
      security:
        - bearerAuth: [SystemAdmin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserGroupRequest'
      responses:
        '201': {}

  /api/admin/user-groups/{groupId}/operations:
    put:
      tags: [Admin]
      summary: جایگزینی عملیات گروه
      security:
        - bearerAuth: [SystemAdmin]
      parameters:
        - $ref: '#/components/parameters/GroupId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items: { type: string }
      responses:
        '204': {}

  /api/admin/operations:
    get:
      tags: [Admin]
      summary: لیست تمام عملیات سیستم (منو + دسترسی)
      security:
        - bearerAuth: [SystemAdmin]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperationDto'

components:
  parameters:
    GroupId:
      name: groupId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    RegisterRequest:
      type: object
      required: [mobile, fullName]
      properties:
        mobile:     { type: string, pattern: ^\+98\d{10}$ }
        fullName:   { type: string }
        email:      { type: string, format: email }
        userType:   { type: string, enum: [Customer, Vendor] }

    RegisterResponse:
      type: object
      properties:
        userId:   { type: string, format: uuid }
        message:  { type: string, example: "کد تأیید ارسال شد" }

    VerifyOtpRequest:
      type: object
      required: [mobile, code]
      properties:
        mobile: { type: string }
        code:   { type: string, pattern: ^\d{6}$ }

    PasswordLoginRequest:
      type: object
      required: [mobile, password]
      properties:
        mobile:    { type: string }
        password:  { type: string, format: password }

    TokenResponse:
      type: object
      properties:
        accessToken:   { type: string }
        refreshToken:  { type: string }
        expiresIn:     { type: integer, example: 3600 }
        tokenType:     { type: string, example: Bearer }
        user:          { $ref: '#/components/schemas/CurrentUserDto' }

    CurrentUserDto:
      type: object
      properties:
        userId:       { type: string, format: uuid }
        fullName:     { type: string }
        mobile:       { type: string }
        email:        { type: string }
        userType:     { type: string, enum: [Customer, Vendor, SystemAdmin, Supplier, OrderSupport, DeliveryAgent] }
        groups:       { type: array, items: { type: string } }
        permissions:  { type: array, items: { type: string } }

    MenuItemDto:
      type: object
      properties:
        code:       { type: string }
        title:      { type: string }
        path:       { type: string }
        icon:       { type: string }
        sortOrder:  { type: integer }
        children:   { type: array, items: { $ref: '#/components/schemas/MenuItemDto' } }

    UserGroupDto:
      type: object
      properties:
        groupId:        { type: string, format: uuid }
        code:           { type: string }
        name:           { type: string }
        description:    { type: string }
        isSystem:       { type: boolean }
        operationCodes: { type: array, items: { type: string } }

    CreateUserGroupRequest:
      type: object
      required: [code, name]
      properties:
        code:        { type: string }
        name:        { type: string }
        description: { type: string }
        isSystem:    { type: boolean, default: false }

    OperationDto:
      type: object
      properties:
        operationId: { type: string, format: uuid }
        code:        { type: string }
        name:        { type: string }
        category:    { type: string }
        menuPath:    { type: string, nullable: true }
        menuTitle:   { type: string }
        icon:        { type: string }
        sortOrder:   { type: integer }

    PagedUserAdminDto:
      type: object
      properties:
        total: { type: integer }
        items:
          type: array
          items:
            type: object
            properties:
              userId:   { type: string, format: uuid }
              fullName: { type: string }
              mobile:   { type: string }
              groups:   { type: array, items: { type: string } }
              status:   { type: string }

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []