# filename: product-service.yaml
openapi: 3.0.3
info:
  title: Product Service API
  version: 1.3.0
  description: >
    سرویس کاتالوگ محصولات پلتفرم بازار خرده‌فروشی مواد غذایی  
    مدیریت SKU، موجودی چندفروشگاهی، قیمت‌گذاری پویا، تخفیف‌های چندلایه، آپلود دسته‌ای،  
    همگام‌سازی با فروشگاه‌های زنجیره‌ای (رفاه، شهروند، هایپراستار و ...) و پشتیبانی کامل چندزبانه/چندارزی.
servers:
  - url: https://api.marketplace.local/product
    description: Production
  - url: https://api.marketplace.sbx/product
    description: Sandbox
tags:
  - name: Products
    description: عملیات CRUD و جستجوی محصولات
  - name: Inventory
    description: مدیریت موجودی و رزرو
  - name: Pricing
    description: محاسبه قیمت نهایی و تخفیف‌ها
  - name: Bulk
    description: آپلود و همگام‌سازی دسته‌ای
  - name: Categories
    description: دسته‌بندی‌های غذایی
  - name: Admin
    description: عملیات مدیریتی و تأیید محتوا
paths:
  /api/products:
    get:
      tags: [Products]
      summary: جستجو و فیلتر پیشرفته محصولات
      parameters:
        - name: q
          in: query
          description: متن جستجو (عنوان، برند، بارکد)
          schema:
            type: string
        - name: categoryId
          in: query
          schema:
            type: string
            format: uuid
        - name: storeId
          in: query
          description: فیلتر بر اساس فروشگاه خاص
          schema:
            type: string
            format: uuid
        - name: vendorId
          in: query
          schema:
            type: string
        - name: minPrice
          in: query
          schema:
            type: number
        - name: maxPrice
          in: query
          schema:
            type: number
        - name: brand
          in: query
          schema:
            type: string
        - name: rating
          in: query
          schema:
            type: number
            minimum: 0
            maximum: 5
        - name: inStock
          in: query
          schema:
            type: boolean
        - name: sort
          in: query
          schema:
            type: string
            enum: [relevance, price_asc, price_desc, newest, bestselling, rating]
            default: relevance
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 24
      responses:
        '200':
          description: لیست محصولات
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedProductResponse'

    post:
      tags: [Products, Admin]
      summary: ایجاد محصول جدید (فقط فروشنده یا مدیر)
      security:
        - bearerAuth: [Vendor, Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: محصول ایجاد شد
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'

  /api/products/{productId}:
    get:
      tags: [Products]
      summary: جزئیات کامل محصول
      parameters:
        - $ref: '#/components/parameters/ProductId'
      responses:
        '200':
          description: محصول
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetailDto'

    put:
      tags: [Products]
      summary: ویرایش کامل محصول
      security:
        - bearerAuth: [Vendor, Admin]
      parameters:
        - $ref: '#/components/parameters/ProductId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        '200':
          description: بروزرسانی موفق

    patch:
      tags: [Products, Admin]
      summary: تغییر وضعیت محصول (تأیید/رد/مسدود)
      security:
        - bearerAuth: [Admin]
      parameters:
        - $ref: '#/components/parameters/ProductId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/ProductStatus'
                reason:
                  type: string
      responses:
        '204':
          description: وضعیت تغییر کرد

  /api/products/{productId}/inventory:
    get:
      tags: [Inventory]
      summary: موجودی محصول در فروشگاه‌های مختلف
      parameters:
        - $ref: '#/components/parameters/ProductId'
      responses:
        '200':
          description: موجودی‌ها
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StoreInventoryDto'

    patch:
      tags: [Inventory]
      summary: بروزرسانی موجودی توسط فروشنده (یا همگام‌سازی خودکار)
      security:
        - bearerAuth: [Vendor, RetailIntegration]
      parameters:
        - $ref: '#/components/parameters/ProductId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInventoryRequest'
      responses:
        '204':
          description: موجودی بروز شد

  /api/products/pricing/calculate:
    post:
      tags: [Pricing]
      summary: محاسبه قیمت نهایی با تمام تخفیف‌ها
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PricingCalculationRequest'
      responses:
        '200':
          description: قیمت نهایی
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PricingCalculationResponse'

  /api/products/bulk/upload:
    post:
      tags: [Bulk]
      summary: آپلود دسته‌ای محصولات (CSV یا Excel)
      security:
        - bearerAuth: [Vendor, Admin]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                storeId:
                  type: string
                  format: uuid
      responses:
        '202':
          description: فایل دریافت و در صف پردازش قرار گرفت
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkUploadResponse'

  /api/categories:
    get:
      tags: [Categories]
      summary: لیست تمام دسته‌بندی‌های غذایی
      responses:
        '200':
          description: درخت دسته‌بندی
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'

components:
  parameters:
    ProductId:
      name: productId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: PRD-2025-000123

  schemas:
    ProductStatus:
      type: string
      enum: [Draft, PendingReview, Approved, Rejected, Suspended, Discontinued]

    ProductDto:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        sku:
          type: string
        barcode:
          type: string
        title:
          type: object
          additionalProperties:
            type: string
          description: عنوان به زبان‌های مختلف (fa, en, ar, ...)
        description:
          type: object
          additionalProperties:
            type: string
        brand:
          type: string
        categoryId:
          type: string
          format: uuid
        vendorId:
          type: string
          format: uuid
        basePrice:
          type: number
        currency:
          $ref: '#/components/schemas/Currency'
        status:
          $ref: '#/components/schemas/ProductStatus'
        images:
          type: array
          items:
            type: string
            format: uri
        tags:
          type: array
          items:
            type: string
        isPerishable:
          type: boolean
        weightGram:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProductDetailDto:
      allOf:
        - $ref: '#/components/schemas/ProductDto'
        - type: object
          properties:
            inventory:
              type: array
              items:
                $ref: '#/components/schemas/StoreInventoryDto'
            finalPrice:
              $ref: '#/components/schemas/PricingInfo'
            rating:
              type: number
              format: float
            reviewCount:
              type: integer

    CreateProductRequest:
      type: object
      required: [sku, title, basePrice, currency, categoryId, vendorId]
      properties:
        sku:
          type: string
        barcode:
          type: string
        title:
          type: object
          additionalProperties:
            type: string
        description:
          type: object
          additionalProperties:
            type: string
        brand:
          type: string
        categoryId:
          type: string
          format: uuid
        vendorId:
          type: string
          format: uuid
        basePrice:
          type: number
        currency:
          $ref: '#/components/schemas/Currency'
        images:
          type: array
          items:
            type: string
            format: uri
        tags:
          type: array
          items:
            type: string
        weightGram:
          type: integer
        isPerishable:
          type: boolean

    UpdateProductRequest:
      allOf:
        - $ref: '#/components/schemas/CreateProductRequest'
        - type: object
          properties:
            productId:
              type: string
              format: uuid

    StoreInventoryDto:
      type: object
      properties:
        storeId:
          type: string
          format: uuid
        storeName:
          type: string
        available:
          type: integer
        reserved:
          type: integer
        lowStockThreshold:
          type: integer
          default: 10
        lastUpdated:
          type: string
          format: date-time

    UpdateInventoryRequest:
      type: object
      required: [storeId, available]
      properties:
        storeId:
          type: string
          format: uuid
        available:
          type: integer
          minimum: 0
        reserved:
          type: integer
          minimum: 0

    PricingCalculationRequest:
      type: object
      required: [productId, storeId, quantity]
      properties:
        productId:
          type: string
          format: uuid
        storeId:
          type: string
          format: uuid
        quantity:
          type: integer
          default: 1
        customerId:
          type: string
          format: uuid
          description: برای اعمال تخفیف شخصی
        couponCode:
          type: string

    PricingInfo:
      type: object
      properties:
        basePrice:
          type: number
        finalPrice:
          type: number
        discountAmount:
          type: number
        discountPercent:
          type: number
        appliedDiscounts:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [System, Campaign, Vendor, Customer, Coupon]
              amount:
                type: number
              name:
                type: string

    PricingCalculationResponse:
      type: object
      properties:
        productId:
          type: string
        pricing:
          $ref: '#/components/schemas/PricingInfo'
        currency:
          $ref: '#/components/schemas/Currency'

    BulkUploadResponse:
      type: object
      properties:
        jobId:
          type: string
          format: uuid
        status:
          type: string
          enum: [Queued, Processing, Completed, Failed]
        totalRecords:
          type: integer
        processedRecords:
          type: integer
        failedRecords:
          type: integer
        downloadReportUrl:
          type: string
          format: uri
          nullable: true

    CategoryDto:
      type: object
      properties:
        categoryId:
          type: string
          format: uuid
        name:
          type: object
          additionalProperties:
            type: string
        parentId:
          type: string
          format: uuid
          nullable: true
        imageUrl:
          type: string
          format: uri
        sortOrder:
          type: integer
        children:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDto'

    PagedProductResponse:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'

    Currency:
      type: string
      enum: [IRR, AED, USD, EUR, TRY]
      default: IRR

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
        detail:
          type: string
        status:
          type: integer
        traceId:
          type: string

  responses:
    BadRequest:
      description: درخواست نامعتبر
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []